<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\FinancialPlannSol;

class FinancialPlanningSolutionList extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        date_default_timezone_set('Asia/Manila');
        $data = [
            [
                'q_finPlSo_clientID' => "C40920220725164403665",
                'q_finPlSo_forTable' => "FAMILY PROTECTION/CLEANUP FUND",
                'q_finPlSo_monthlyBud1' => 1128.65,
                'q_finPlSo_monthlyBud2' => 3128.65,
                'q_finPlSo_actNetCashflow1' => 6892.55,
                'q_finPlSo_actNetCashflow2' => 69956.22,
                'q_finPlSo_advisorSuggestion' => "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-11-23",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
            ],
            [
                'q_finPlSo_clientID' => "C40920220725164403665",
                'q_finPlSo_forTable' => "HEALTH FUND",
                'q_finPlSo_monthlyBud1' => 59591.65,
                'q_finPlSo_monthlyBud2' => 3555.65,
                'q_finPlSo_actNetCashflow1' => 222.55,
                'q_finPlSo_actNetCashflow2' => 4444.22,
                'q_finPlSo_advisorSuggestion' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-9-13",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
            ],
            [
                'q_finPlSo_clientID' => "C40920220725164403665",
                'q_finPlSo_forTable' => "RETIREMENT FUND",
                'q_finPlSo_monthlyBud1' => 12344.55,
                'q_finPlSo_monthlyBud2' => 54331.21,
                'q_finPlSo_actNetCashflow1' => 222.55,
                'q_finPlSo_actNetCashflow2' => 4444.22,
                'q_finPlSo_advisorSuggestion' => "Lorem ipsum dolor ore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-8-23",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
            ],
            [
                'q_finPlSo_clientID' => "C40920230227135120974",
                'q_finPlSo_forTable' => "RETIREMENT FUND",
                'q_finPlSo_monthlyBud1' => 88232.23,
                'q_finPlSo_monthlyBud2' => 44126.77,
                'q_finPlSo_actNetCashflow1' => 23461.22,
                'q_finPlSo_actNetCashflow2' => 23156.11,
                'q_finPlSo_advisorSuggestion' => "Lorem ipsum dolor ore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-8-23",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
            ],
            [
                'q_finPlSo_clientID' => "C40920230227135120974",
                'q_finPlSo_forTable' => "CHILDREN'S EDUCATION FUND",
                'q_finPlSo_monthlyBud1' => 1233.23,
                'q_finPlSo_monthlyBud2' => 234236.77,
                'q_finPlSo_actNetCashflow1' => 5125.22,
                'q_finPlSo_actNetCashflow2' => 3421.11,
                'q_finPlSo_advisorSuggestion' => "rom its medieval origins to the digital era, learn everything there is to know about the ubiquitous lorem ipsum passage.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-7-15",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
            ],
            [
                'q_finPlSo_clientID' => "C40920230227135120974",
                'q_finPlSo_forTable' => "FAMILY PROTECTION/CLEANUP FUND",
                'q_finPlSo_monthlyBud1' => 8676.23,
                'q_finPlSo_monthlyBud2' => 56475.77,
                'q_finPlSo_actNetCashflow1' => 3456.22,
                'q_finPlSo_actNetCashflow2' => 456848.11,
                'q_finPlSo_advisorSuggestion' => "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book. It usually begins with.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-12-22",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
            ],
            [
                'q_finPlSo_clientID' => "C41120210822130949887",
                'q_finPlSo_forTable' => "HEALTH FUND",
                'q_finPlSo_monthlyBud1' => 8676.23,
                'q_finPlSo_monthlyBud2' => 56475.77,
                'q_finPlSo_actNetCashflow1' => 3456.22,
                'q_finPlSo_actNetCashflow2' => 456848.11,
                'q_finPlSo_advisorSuggestion' => "Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book. It usually begins with.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-12-22",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
            ],
            [
                'q_finPlSo_clientID' => "C41120210822130949887",
                'q_finPlSo_forTable' => "RETIREMENT FUND",
                'q_finPlSo_monthlyBud1' => 6123.23,
                'q_finPlSo_monthlyBud2' => 2412.77,
                'q_finPlSo_actNetCashflow1' => 3443.22,
                'q_finPlSo_actNetCashflow2' => 1235.11,
                'q_finPlSo_advisorSuggestion' => "om its medieval origins to the digital era, learn everything there is to know about the ubiquitous lorem ipsum passage.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-12-21",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
                'q_finPlSo_dateMarkedAsResolved' => "2024-06-04",
                'q_finPlSo_remarksOnResolved' => "hdfg dfg er gerjfghfd hr tt yj ghjwre efsdfse"
            ],
            [
                'q_finPlSo_clientID' => "C41120210822130949887",
                'q_finPlSo_forTable' => "CHILDREN'S EDUCATION FUND",
                'q_finPlSo_monthlyBud1' => 123.23,
                'q_finPlSo_monthlyBud2' => 42.77,
                'q_finPlSo_actNetCashflow1' => 34.22,
                'q_finPlSo_actNetCashflow2' => 512.11,
                'q_finPlSo_advisorSuggestion' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-11-21",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
                'q_finPlSo_dateMarkedAsResolved' => "2024-06-04",
                'q_finPlSo_remarksOnResolved' => "hdfg d r ger yuy fgfth"
            ],
            [
                'q_finPlSo_clientID' => "C41120210822134918579",
                'q_finPlSo_forTable' => "FAMILY PROTECTION/CLEANUP FUND",
                'q_finPlSo_monthlyBud1' => 1512.23,
                'q_finPlSo_monthlyBud2' => 2343.77,
                'q_finPlSo_actNetCashflow1' => 354524.22,
                'q_finPlSo_actNetCashflow2' => 2342.11,
                'q_finPlSo_advisorSuggestion' => "publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-7-2",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
            ],
            [
                'q_finPlSo_clientID' => "C41120210822134918579",
                'q_finPlSo_forTable' => "HEALTH FUND",
                'q_finPlSo_monthlyBud1' => 23423.23,
                'q_finPlSo_monthlyBud2' => 5462.77,
                'q_finPlSo_actNetCashflow1' => 512332.22,
                'q_finPlSo_actNetCashflow2' => 23423.11,
                'q_finPlSo_advisorSuggestion' => "publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-7-2",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
                'q_finPlSo_dateMarkedAsResolved' => "2024-06-04",
                'q_finPlSo_remarksOnResolved' => "hdf dr g erg df df"
            ],
            [
                'q_finPlSo_clientID' => "C41120210823145713653",
                'q_finPlSo_forTable' => "RETIREMENT FUND",
                'q_finPlSo_monthlyBud1' => 34545.361,
                'q_finPlSo_monthlyBud2' => 523462.53,
                'q_finPlSo_actNetCashflow1' => 3344.77,
                'q_finPlSo_actNetCashflow2' => 54522.45,
                'q_finPlSo_advisorSuggestion' => "publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-6-2",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
            ],
            [
                'q_finPlSo_clientID' => "C41120210823145713653",
                'q_finPlSo_forTable' => "CHILDREN'S EDUCATION FUND",
                'q_finPlSo_monthlyBud1' => 33342.665,
                'q_finPlSo_monthlyBud2' => 234532.4356,
                'q_finPlSo_actNetCashflow1' => 6456674.22,
                'q_finPlSo_actNetCashflow2' => 33355.33,
                'q_finPlSo_advisorSuggestion' => "was Latin. Richard McClintock, a Latin scholar from Hampden-Sydney College, is credited with discovering the source behind the ubiquitous filler text. In seeing a sample of lorem ipsum, his interest was piqued by consectetur—a genuine, albeit rare, Latin word. Consulting a Latin dictionary led McClintock to a passage from De Finibus Bonorum et Malorum (“On the Extremes of Good and Evil”), a first-century B.C. text from the Roman philosopher Cicero. In particular, the garbled words of lorem ipsum bear an unm.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-7-7",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
            ],
            [
                'q_finPlSo_clientID' => "C41120210905011233199",
                'q_finPlSo_forTable' => "FAMILY PROTECTION/CLEANUP FUND",
                'q_finPlSo_monthlyBud1' => 34522.22,
                'q_finPlSo_monthlyBud2' => 66663.224,
                'q_finPlSo_actNetCashflow1' => 23444.122,
                'q_finPlSo_actNetCashflow2' => 666612.343,
                'q_finPlSo_advisorSuggestion' => "McClintock's eye for detail certainly helped narrow the whereabouts of lorem ipsum's origin, however, the “how and when” still remain something of a mystery, with competing theories and timelines.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-5-1",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
            ],
            [
                'q_finPlSo_clientID' => "C41120210905011233199",
                'q_finPlSo_forTable' => "HEALTH FUND",
                'q_finPlSo_monthlyBud1' => 3333.441,
                'q_finPlSo_monthlyBud2' => 1111.222,
                'q_finPlSo_actNetCashflow1' => 2222.44,
                'q_finPlSo_actNetCashflow2' => 5555.43,
                'q_finPlSo_advisorSuggestion' => "McClintock's eye for detail certainly helped narrow the whereabouts of lorem ipsum's origin, however, the “how and when” still remain something of a mystery, with competing theories and timelines.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-4-28",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
            ],
            [
                'q_finPlSo_clientID' => "C41120210905011924272",
                'q_finPlSo_forTable' => "RETIREMENT FUND",
                'q_finPlSo_monthlyBud1' => 523345.441,
                'q_finPlSo_monthlyBud2' => 3345.222,
                'q_finPlSo_actNetCashflow1' => 55553.44,
                'q_finPlSo_actNetCashflow2' => 334455.43,
                'q_finPlSo_advisorSuggestion' => "Nor is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but occasionally circumstances occur in which toil and pain can procure him some great pleasure.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-2-11",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
            ],
            [
                'q_finPlSo_clientID' => "C41120210905012059895",
                'q_finPlSo_forTable' => "FAMILY PROTECTION/CLEANUP FUND",
                'q_finPlSo_monthlyBud1' => 767324.441,
                'q_finPlSo_monthlyBud2' => 5553.222,
                'q_finPlSo_actNetCashflow1' => 64534.44,
                'q_finPlSo_actNetCashflow2' => 22223.43,
                'q_finPlSo_advisorSuggestion' => "In particular, the garbled words of lorem ipsum bear an unmistakable resemblance to sections 1.10.32–33 of Cicero's work, with the most notable passage excerpted below:",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-2-11",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
            ],
            [
                'q_finPlSo_clientID' => "C41120240510161859897",
                'q_finPlSo_forTable' => "HEALTH FUND",
                'q_finPlSo_monthlyBud1' => 6723.441,
                'q_finPlSo_monthlyBud2' => 4354.222,
                'q_finPlSo_actNetCashflow1' => 6562.44,
                'q_finPlSo_actNetCashflow2' => 1123443.43,
                'q_finPlSo_advisorSuggestion' => "overing the source behind the ubiquitous filler text. In seeing a sample of lorem ipsum, his interest was piqued by consectetur—a genuine, albeit rare, Latin word. Consulting a Latin dictionary led McClintock to a passage from De Finibus Bonorum et Malorum (“On the Extremes of Good and Evil”), a first-century B.C. text from the Roman philosopher Cicer",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-5-29",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
            ],
            [
                'q_finPlSo_clientID' => "C41120210930200107172",
                'q_finPlSo_forTable' => "RETIREMENT FUND",
                'q_finPlSo_monthlyBud1' => 7456456.441,
                'q_finPlSo_monthlyBud2' => 34545.222,
                'q_finPlSo_actNetCashflow1' => 75676.44,
                'q_finPlSo_actNetCashflow2' => 23434.43,
                'q_finPlSo_advisorSuggestion' => "reation timelines for the standard lorem ipsum passage vary, with some citing the 15th century and others",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-8-29",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
            ],
            [
                'q_finPlSo_clientID' => "C41120210905011233199",
                'q_finPlSo_forTable' => "CHILDREN'S EDUCATION FUND",
                'q_finPlSo_monthlyBud1' => 5155.441,
                'q_finPlSo_monthlyBud2' => 55213.222,
                'q_finPlSo_actNetCashflow1' => 45532.44,
                'q_finPlSo_actNetCashflow2' => 441255.43,
                'q_finPlSo_advisorSuggestion' => "find examples of lorem ipsum in use before Letraset made it popular as a dummy text in the 1960s, although McClintock says he remembers coming across the lorem ipsum passage in a book of old metal type samples. So far he hasn't relocated where he once saw the passage, but the popularity of Cicero i.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-7-29",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
            ],
            [
                'q_finPlSo_clientID' => "C41120210905011233199",
                'q_finPlSo_forTable' => "FAMILY PROTECTION/CLEANUP FUND",
                'q_finPlSo_monthlyBud1' => 566123.441,
                'q_finPlSo_monthlyBud2' => 4444.222,
                'q_finPlSo_actNetCashflow1' => 55245.44,
                'q_finPlSo_actNetCashflow2' => 23554.43,
                'q_finPlSo_advisorSuggestion' => "find examples of lorem ipsumpassage in a book of old metal type samples. So far he hasn't relocated where he once saw the passage, but the popularity of Cicero i.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-8-29",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
            ],
            [
                'q_finPlSo_clientID' => "C41120210905011924272",
                'q_finPlSo_forTable' => "HEALTH FUND",
                'q_finPlSo_monthlyBud1' => 88668.441,
                'q_finPlSo_monthlyBud2' => 4448884.222,
                'q_finPlSo_actNetCashflow1' => 888865.44,
                'q_finPlSo_actNetCashflow2' => 23888554.43,
                'q_finPlSo_advisorSuggestion' => "find examples of lor a book of old metal type samples. So far he hasn't relocated where he once saw the passage, but the popularity of Cicero i.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-7-21",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
                'q_finPlSo_dateMarkedAsResolved' => "2024-06-04",
                'q_finPlSo_remarksOnResolved' => "gdf gd g reg er gqwd wd ds sdferg er gdf gdrgege"
            ],
            [
                'q_finPlSo_clientID' => "C41120210905012059895",
                'q_finPlSo_forTable' => "FAMILY PROTECTION/CLEANUP FUND",
                'q_finPlSo_monthlyBud1' => 774666.441,
                'q_finPlSo_monthlyBud2' => 6634566.222,
                'q_finPlSo_actNetCashflow1' => 4536673.44,
                'q_finPlSo_actNetCashflow2' => 5555.43,
                'q_finPlSo_advisorSuggestion' => "ne brave soul did take a stab at translating the almost-not-quite-Latin. According to The Guardian, Jaspreet Singh Boparai undertook the challenge with the goal of making the text “precisely as incoherent in English as it is in Latin - and to make it incoherent in the same way”. As a result, “the Greek 'eu' in Latin became the French 'bien' [...] and the '-ing' ending in 'lorem ipsum' seemed best rendered by an '-iendum' in English.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-7-21",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
            ],
            [
                'q_finPlSo_clientID' => "C41120210905012525315",
                'q_finPlSo_forTable' => "HEALTH FUND",
                'q_finPlSo_monthlyBud1' => 613345.441,
                'q_finPlSo_monthlyBud2' => 5234523.222,
                'q_finPlSo_actNetCashflow1' => 44234.44,
                'q_finPlSo_actNetCashflow2' => 556233.43,
                'q_finPlSo_advisorSuggestion' => "ne brave soul did take a stab at translating the almost-not-quite-Latin. According to The Guardian, Jaspreet Singh Boparai undertook the challenge with tha result, “the Greek 'eu' in Latin became the French 'bien' [...] and the '-ing' ending in 'lorem ipsum' seemed best rendered by an '-iendum' in English.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-8-5",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
            ],
            [
                'q_finPlSo_clientID' => "C1202111080558445524",
                'q_finPlSo_forTable' => "RETIREMENT FUND",
                'q_finPlSo_monthlyBud1' => 534636.441,
                'q_finPlSo_monthlyBud2' => 45555.222,
                'q_finPlSo_actNetCashflow1' => 23444.44,
                'q_finPlSo_actNetCashflow2' => 552632.43,
                'q_finPlSo_advisorSuggestion' => "ne brave soul did take a stab at transl According to The Guardian, Jaspreet Singh Boparai undertook the challenge with tha result, “the Greek 'eu' in Latin became the French 'bien' [...] and the '-ing' ending in 'lorem ipsum' seemed best rendered by an '-iendum' in English.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-7-15",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
            ],
            [
                'q_finPlSo_clientID' => "C41120210318050413733",
                'q_finPlSo_forTable' => "CHILDREN'S EDUCATION FUND",
                'q_finPlSo_monthlyBud1' => 764545.441,
                'q_finPlSo_monthlyBud2' => 55344.222,
                'q_finPlSo_actNetCashflow1' => 25523.44,
                'q_finPlSo_actNetCashflow2' => 344356.43,
                'q_finPlSo_advisorSuggestion' => "ne brave soul did take a stab at transl Accord'bien' and the '-ing' ending in 'lorem ipsum' seemed best rendered by an '-iendum' in English.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-8-21",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
            ],
            [
                'q_finPlSo_clientID' => "C41120210415162157810",
                'q_finPlSo_forTable' => "FAMILY PROTECTION/CLEANUP FUND", 
                'q_finPlSo_monthlyBud1' => 6345345.441,
                'q_finPlSo_monthlyBud2' => 6345733.222,
                'q_finPlSo_actNetCashflow1' => 634634.44,
                'q_finPlSo_actNetCashflow2' => 45347634.43,
                'q_finPlSo_advisorSuggestion' => "ne brave sadwe w ef we e fsdf we ywqweqw qweqw w sd fwe fwe sdf yertry erwer we sdf w fedfg df ger soul did take a stab at transl Accom' seemed best rendered by an '-iendum' in English.",
                'q_finPlSo_status' => 2,
                'q_finPlSo_goalRev' => 1,
                'q_finPlSo_meetAdvisorOn' => "2024-11-21",
                'q_finPlSo_dateUpdated' => "2024-05-12",
                'q_finPlSo_dateCreated' => "2024-05-12",
            ],
        ];
        foreach ($data as $item) {
            FinancialPlannSol::create($item);
        }
    }
}
