<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Todos;

class ToDosSampleData extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        date_default_timezone_set('Asia/Manila');
        $data = [
            [
                'q_tdo_clientID' => 'C41120210728133552401',
                'q_tdo_agentID' => 411,
                'q_tdo_isForClientAgent' => 1,
                'q_tdo_descripx' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                'q_tdo_dateTodo' => '2024-4-10',
                'q_tdo_fromTable' => 'FAMILY PROTECTION/CLEANUP FUND',
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C41120210728133552401',
                'q_tdo_agentID' => 411,
                'q_tdo_isForClientAgent' => 1,
                'q_tdo_descripx' => 'Check out our new font generator and level up your social bios. Need more? Head over to Glyphy for all the fancy fonts and cool symbols you could ever imagine. And don’t forget, we have images, plugins and the ultimate guide to all flavors of lorem ipsum.',
                'q_tdo_dateTodo' => '2024-5-21',
                'q_tdo_fromTable' => 'FAMILY PROTECTION/CLEANUP FUND',
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C41120210614204001475',
                'q_tdo_agentID' => 411,
                'q_tdo_isForClientAgent' => 2,
                'q_tdo_descripx' => "The purpose of lorem ipsum is to create a natural looking block of text (sentence, paragraph, page, etc.) that doesn't distract from the layout. A practice not without controversy, laying out pages with meaningless filler text can be very useful when the focus is meant to be on design, not content. The passage experienced a surge in popularity during the 1960s when Letraset used it on their dry-transfer sheets, and again during the 90s as desktop publishers bundled the text with their software. Today it's seen all around the web; on templates, websites, and stock designs. Use our generator to get your own, or read on for the authoritative history of lorem ipsum.",
                'q_tdo_dateTodo' => '2024-6-4',
                'q_tdo_fromTable' => 'HEALTH FUND',
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C41120210914221934803',
                'q_tdo_agentID' => 411,
                'q_tdo_isForClientAgent' => 2,
                'q_tdo_descripx' => "McClintock's eye for detail certainly helped narrow the whereabouts of lorem ipsum's origin, however, the “how and when”still remain something of a mystery, with competing theories and timelines.",
                'q_tdo_dateTodo' => '2024-5-19',
                'q_tdo_fromTable' => 'HEALTH FUND',
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C41120210914221934803',
                'q_tdo_agentID' => 411,
                'q_tdo_isForClientAgent' => 2,
                'q_tdo_descripx' => "So how did the classical Latin become so incoherent? According to McClintock, a 15th century typesetter likely scrambled part of Cicero's De Finibus in order to provide placeholder text to mockup various fonts for a type specimen book. It's difficult to find examples of lorem ipsum in use before Letraset made it popular as a dummy text in the 1960s, although McClintock says he remembers coming across the lorem ipsum passage in a book of old metal type samples. So far he hasn't relocated where he once saw the passage, but the popularity of Cicero in the 15th century supports the theory that the filler text has been used for centuries.",
                'q_tdo_dateTodo' => '2024-5-31',
                'q_tdo_fromTable' => 'FAMILY PROTECTION/CLEANUP FUND',
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C41120210930200107172',
                'q_tdo_agentID' => 411,
                'q_tdo_isForClientAgent' => 1,
                'q_tdo_descripx' => "What I find remarkable is that this text has been the industry's standard dummy text ever since some printer in the 1500s took a galley of type and scrambled it to make a type specimen book; it has survived not only four centuries of letter-by-letter resetting but even the leap into electronic typesetting, essentially unchanged except for an occasional 'ing' or 'y' thrown in. It's ironic that when the then-understood Latin was scrambled, it became as incomprehensible as Greek; the phrase 'it's Greek to me' and 'greeking' have common semantic roots!” (The editors published his letter in a correction headlined “Lorem Oopsum”.",
                'q_tdo_dateTodo' => '2024-5-10',
                'q_tdo_fromTable' => 'FAMILY PROTECTION/CLEANUP FUND',
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C41120210930200107172',
                'q_tdo_agentID' => 411,
                'q_tdo_isForClientAgent' => 1,
                'q_tdo_descripx' => "As an alternative theory, (and because Latin scholars do this sort of thing) someone tracked down a 1914 Latin edition of De Finibus which challenges McClintock's 15th century claims and suggests that the dawn of lorem ipsum was as recent as the 20th century. The 1914 Loeb Classical Library Edition ran out of room on page 34 for the Latin phrase “dolorem ipsum” (sorrow in itself). Thus, the truncated phrase leaves one page dangling with “do-”, while another begins with the now ubiquitous “lorem ipsum”.",
                'q_tdo_dateTodo' => '2024-5-4',
                'q_tdo_fromTable' => 'RETIREMENT FUND',
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C41120210614204001475',
                'q_tdo_agentID' => 411,
                'q_tdo_isForClientAgent' => 1,
                'q_tdo_descripx' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam hendrerit nisi sed sollicitudin pellentesque. Nunc posuere purus rhoncus pulvinar aliquam. Ut aliquet tristique nisl vitae volutpat. Nulla aliquet porttitor venenatis. Donec a dui et dui fringilla consectetur id nec massa. Aliquam erat volutpat. Sed ut dui ut lacus dictum fermentum vel tincidunt neque. Sed sed lacinia lectus. Duis sit amet sodales felis. Duis nunc eros, mattis at dui ac, convallis semper risus. In adipiscing ultrices tellus, in suscipit massa vehicula eu.",
                'q_tdo_dateTodo' => '2024-5-19',
                'q_tdo_fromTable' => "CHILDREN'S EDUCATION FUND",
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C41120210914221934803',
                'q_tdo_agentID' => 411,
                'q_tdo_isForClientAgent' => 1,
                'q_tdo_descripx' => "Nick Richardson described the translation “like extreme Mallarmé, or a Burroughsian cut-up, or a paragraph of Finnegans Wake. Bits of it have surprising power: the desperate insistence on loving and pursuing sorrow, for instance, that is cheated out of its justification – an incomplete object that has been either fished for, or wished for.",
                'q_tdo_dateTodo' => '2024-5-12',
                'q_tdo_fromTable' => "CHILDREN'S EDUCATION FUND",
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C41120210930200107172',
                'q_tdo_agentID' => 411,
                'q_tdo_isForClientAgent' => 1,
                'q_tdo_descripx' => "or at least what used to be Cicero—in an attempt to make the days before computerized design a little less painstaking. The French lettering company Letraset manufactured a set of dry-transfer sheets which included the lorem ipsum filler text in a variety of fonts, sizes, and layouts. These sheets of lettering could be rubbed on anywhere and were quickly adopted by graphic artists, printers, architects, and advertisers for their professional look and ease of use.",
                'q_tdo_dateTodo' => '2024-6-12',
                'q_tdo_fromTable' => 'RETIREMENT FUND',
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'RETIREMENT FUND',
                'q_tdo_agentID' => 411,
                'q_tdo_isForClientAgent' => 2,
                'q_tdo_descripx' => "Original Source Text Below are the original Latin passages from which Lorem Ipsum was derived, paired with their 1914 translations by H. Rackham.",
                'q_tdo_dateTodo' => '2024-5-16',
                'q_tdo_fromTable' => 'CASH FLOW',
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C41120210415162157810',
                'q_tdo_agentID' => 411,
                'q_tdo_isForClientAgent' => 2,
                'q_tdo_descripx' => "Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit amet consectetur adipisci[ng] velit, sed quia non numquam [do] eius modi tempora inci[di]dunt, ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit, qui in ea voluptate velit esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas nulla pariatur?",
                'q_tdo_dateTodo' => '2024-5-18',
                'q_tdo_fromTable' => "CHILDREN'S EDUCATION FUND",
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C41120210415162157810',
                'q_tdo_agentID' => 411,
                'q_tdo_isForClientAgent' => 1,
                'q_tdo_descripx' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                'q_tdo_dateTodo' => '2024-5-29',
                'q_tdo_fromTable' => 'FAMILY PROTECTION/CLEANUP FUND',
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C41120210905011924272',
                'q_tdo_agentID' => 411,
                'q_tdo_isForClientAgent' => 1,
                'q_tdo_descripx' => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                'q_tdo_dateTodo' => '2024-5-19',
                'q_tdo_fromTable' => 'FAMILY PROTECTION/CLEANUP FUND',
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C41120210905012059895',
                'q_tdo_agentID' => 411,
                'q_tdo_isForClientAgent' => 1,
                'q_tdo_descripx' => "t labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
                'q_tdo_dateTodo' => '2024-6-5',
                'q_tdo_fromTable' => 'FAMILY PROTECTION/CLEANUP FUND',
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C41120210822124959504',
                'q_tdo_agentID' => 411,
                'q_tdo_isForClientAgent' => 1,
                'q_tdo_descripx' => "Website and Graphic Design: Lorem Ipsum is widely used by web designers and graphic artists during the development phase of websites, applications, and other digital media. It helps them create mockups and prototypes without being distracted by the actual content. Designers can focus on the layout, typography, and overall aesthetics of the design before the final content is ready",
                'q_tdo_dateTodo' => '2024-5-19',
                'q_tdo_fromTable' => 'HEALTH FUND',
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C41120210822124959504',
                'q_tdo_agentID' => 411,
                'q_tdo_isForClientAgent' => 1,
                'q_tdo_descripx' => "Print Layouts and Typesetting: In the publishing and printing industry, designers often use Lorem Ipsum when creating layouts for books, magazines, brochures, and other printed materials. By using Lorem Ipsum, designers can visualize how the text will flow within the document and make adjustments to the page layout, font choices, and spacing without the need for real content.",
                'q_tdo_dateTodo' => '2024-5-21',
                'q_tdo_fromTable' => 'RETIREMENT FUND',
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C41120210822125059319',
                'q_tdo_agentID' => 411,
                'q_tdo_isForClientAgent' => 1,
                'q_tdo_descripx' => "Presentations and Templates: Lorem Ipsum is also useful in creating presentation templates. When designing presentation slides, professionals can use placeholder text to demonstrate how the text will appear on the slides. This helps in designing visually appealing and balanced slides. Similarly, it's used in document templates, allowing users to see the overall document layout without getting distracted by the actual content.",
                'q_tdo_dateTodo' => '2024-5-19',
                'q_tdo_fromTable' => 'RETIREMENT FUND',
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C41120210822125059319',
                'q_tdo_agentID' => 411,
                'q_tdo_isForClientAgent' => 2,
                'q_tdo_descripx' => "ndustry, designers often use Lorem Ipsum when creating layouts for books, magazines, brochures, and other printed materials. By using Lorem Ipsum, designers can visualize how the text will flow within the document and make adjustments to the page layout, font choices, and spacing without the need for real content. Presentations and Templates: Lorem Ipsum is also useful in creating presentation templates. When designing presentation slides, professionals can use placeholder text to demonstrate how the text will appear on the slides. Th",
                'q_tdo_dateTodo' => '2024-6-1',
                'q_tdo_fromTable' => "CHILDREN'S EDUCATION FUND",
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C41120210822130949887',
                'q_tdo_agentID' => 411,
                'q_tdo_isForClientAgent' => 1,
                'q_tdo_descripx' => "igners and graphic artists during the development phase of websites, applications, and other digital media. It helps them create mockups and prototypes without being distracted by the actual content. Designers can focus on the layout, typography, and overall aesthetics of the design before the final content is ready Print Layouts and Typesetting: In the publishing and printing industry, designers often use Lorem Ipsum when creating layouts for books, magazines, brochures, and other printed materials. By using Lorem Ipsum, design",
                'q_tdo_dateTodo' => '2024-5-31',
                'q_tdo_fromTable' => "CHILDREN'S EDUCATION FUND",
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C1202104040911458705',
                'q_tdo_agentID' => 409,
                'q_tdo_isForClientAgent' => 1,
                'q_tdo_descripx' => "Lorem ipsum was conceived as filler text, formatted in a certain way to enable the presentation of graphic elements in documents, without the need for formal copy. Using Lorem Ipsum allows designers to put together layouts and the form of the content before the content has been created, giving the design and production process more freedom.",
                'q_tdo_dateTodo' => '2024-5-13',
                'q_tdo_fromTable' => 'RETIREMENT FUND',
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C1202104040911458705',
                'q_tdo_agentID' => 409,
                'q_tdo_isForClientAgent' => 1,
                'q_tdo_descripx' => "It is widely believed that the history of Lorem Ipsum originates with Cicero in the 1st Century BC and his text De Finibus bonorum et malorum. This philosophical work, also known as On the Ends of Good and Evil, was split into five books. The Lorem Ipsum we know today is derived from parts of the first book Liber Primus and its discussion on hedonism, the words of which had been altered, added and removed to make it nonsensical and improper Latin. It is not known exactly when the text gained its current traditional form. However references to the phrase lorem ipsum can be found in the 1914 Loeb Classical Library Edition of the De Finibus in sections 32 and 33.",
                'q_tdo_dateTodo' => '2024-5-21',
                'q_tdo_fromTable' => 'HEALTH FUND',
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C1202104040911458705',
                'q_tdo_agentID' => 409,
                'q_tdo_isForClientAgent' => 2,
                'q_tdo_descripx' => "qui dolorem ipsum, quia dolor sit amet consectetur adipisci velit, sed quia non numquam eius modi tempora incidunt, ut labore et dolore magnam aliquam quaerat voluptatem",
                'q_tdo_dateTodo' => '2024-5-16',
                'q_tdo_fromTable' => 'FAMILY PROTECTION/CLEANUP FUND',
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C2355202403211029498189',
                'q_tdo_agentID' => 409,
                'q_tdo_isForClientAgent' => 2,
                'q_tdo_descripx' => "Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but occasionally circumstances occur in which toil and pain can procure him some great pleasure",
                'q_tdo_dateTodo' => '2024-6-1',
                'q_tdo_fromTable' => 'FAMILY PROTECTION/CLEANUP FUND',
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C2355202403211029498189',
                'q_tdo_agentID' => 409,
                'q_tdo_isForClientAgent' => 1,
                'q_tdo_descripx' => "Advancing to the 1960s, Lorem Ipsum was made popular by typeface manufacturer Letraset, who used it in their advertising campaigns. Letraset offered pages of Lorem Ipsum as rub down transfer sheets, which were widely used in the pre-computer era for layouts. These transfer pages, known as Letraset Body Type, were featured in the company's advertising and their popular catalogue",
                'q_tdo_dateTodo' => '2024-5-29',
                'q_tdo_fromTable' => "RETIREMENT FUND",
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C2355202404290531169876',
                'q_tdo_agentID' => 409,
                'q_tdo_isForClientAgent' => 1,
                'q_tdo_descripx' => "Lorem Ipsum was reintroduced in the 1980s by the Aldus Corporation, a company that developed Desktop Publishing Software. Their most well known product PageMaker came with pre-installed graphics and word-processing templates containing a version of the faux latin language",
                'q_tdo_dateTodo' => '2024-5-21',
                'q_tdo_fromTable' => "CHILDREN'S EDUCATION FUND",
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
            [
                'q_tdo_clientID' => 'C409202108121119348374',
                'q_tdo_agentID' => 409,
                'q_tdo_isForClientAgent' => 1,
                'q_tdo_descripx' => "ph durations and punctuation dispersal are calculated using Gaussian distribution, based on statistical analysis of real world texts. This ensures that the generated Lorem Ipsum text is unique, free of repetition and also resembles readable text as much as possible.If you're comfortable with the terminal, you can also install this generator as a command-line application. Provided you have Node.js installed, just execute the following command to install it:",
                'q_tdo_dateTodo' => '2024-5-28',
                'q_tdo_fromTable' => "CHILDREN'S EDUCATION FUND",
                'q_tdo_isSeen' => 0,
                'q_tdo_dateCreated' => date('Y-m-d'),
            ],
        ];
        foreach ($data as $item) {
            Todos::create($item);
        }
    }
}
